# Generated by Django 4.1.7 on 2023-03-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
